-- Find the upward recommendation chain for member ID 27: that is, the member who recommended them, 
--  and the member who recommended that member, and so on.
-- Return member ID, first name, and surname. Order by descending member id.
