-- Find the downward recommendation chain for member ID 1: that is, the members they recommended, 
--  the members those members recommended, and so on.
-- Return member ID and name, and order by ascending member id.
